language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bsl333/docker-react:travis -f Dockerfile.dev .

script:
  - docker run -e CI=true bsl333/docker-react:travis npm run test -- --coverage
